version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.7
    steps:
      - checkout
      - ruby/install-deps

  lint:
    docker:
      - image: cimg/ruby:2.6.7
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Rubocop lint
          command: bundle exec rubocop

  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.6.7
      - image: cimg/postgres:12.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: portrait_api_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: RSpec tests
          command: bundle exec rspec

workflows:
  version: 2
  build_lint_and_test:
    jobs:
      - build
      - lint:
          requires:
          - build
      - test:
          requires:
            - build
            - lint
